server:
  port: 9095

spring:
  application:
  name: crud-operation

  datasource:
    url: jdbc:mysql://localhost:3306/hall_booking
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MuSQL8Dialect
      format_sql: true

